### ISSUE TITLE
Breaks in Terraform 1.6

### ISSUE THREAD

**Issue by aldwyn** [change-engine/terraform-provider-pbkdf2#12]
Hi @BarnabyShearer , 

Thank you so much for creating this TF module.

Just letting you know that the last release tag, i.e. `0.2.4` is breaking on Terraform v1.6, with the following error:
```
╷
│ Error: Resource Type Not Found
│ 
│   with pbkdf2_key.fernet_key,
│   on secrets.tf line 30, in resource "pbkdf2_key" "fernet_key":
│   30: resource "pbkdf2_key" "fernet_key" {
│ 
│ No resource type named "pbkdf2_key" was found in the provider.
╵
```

But I see that you have upgraded the `terraform-plugin-framework` in the main branch, as what was suggested [here](https://github.com/hashicorp/terraform-plugin-framework/issues/853#issuecomment-1752802210). So kindly release a new tag.

Thanks again :)

**Comment by BarnabyShearer** [comment]
Thanks for letting us know.
